AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-sam-sanity

Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String

Resources:
  MyApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Dev
        Domain:
          DomainName: !Ref DomainName
          CertificateArn: !Ref ACMCertificateArn
          EndpointConfiguration: EDGE

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Method: Get
            Path: /
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  HelloWorldFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldCFDomain:
    Description: "https://s.natalian.org/2020-12-09/outputs-domain-name-how.png"
    Value: !GetAtt ApiGatewayDomainName7a4a41c73c.DistributionDomainName
